server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrantonzenkov/config-repo


environment:
  JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true"